# Generated by Django 6.1.1 on 2026-09-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('flagged_count', models.IntegerField(default=0)),
                ('blocked_count', models.IntegerField(default=0)),
                ('cleared_count', models.IntegerField(default=0)),
                ('avg_fraud_score', models.FloatField(blank=True, null=True)),
                ('max_fraud_score', models.FloatField(blank=True, null=True)),
                ('top_flagged_merchant', models.CharField(blank=True, max_length=128)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Stats',
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
            },
        ),
    ]
