# Generated by Django 6.1.1 on 2026-09-06 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('occurred_at', models.DateTimeField(help_text='When the transaction took place.')),
                ('product_type', models.CharField(blank=True, help_text='ProductCD: W H C S R', max_length=8)),
                ('card_number_bin', models.CharField(blank=True, help_text='card1 — first digits of card number', max_length=16)),
                ('card_expiry', models.CharField(blank=True, help_text='card2 — expiry info', max_length=8)),
                ('card_cvv_result', models.CharField(blank=True, help_text='card3 — CVV check result', max_length=8)),
                ('card_type', models.CharField(blank=True, help_text='card4: debit/credit', max_length=32)),
                ('card_network', models.CharField(blank=True, help_text='card5: Visa/MC/Discover/Amex', max_length=32)),
                ('card_bank', models.CharField(blank=True, help_text='card6 — issuing bank', max_length=64)),
                ('p_email_domain', models.CharField(blank=True, help_text='Purchaser email domain', max_length=128)),
                ('r_email_domain', models.CharField(blank=True, help_text='Recipient email domain', max_length=128)),
                ('addr1', models.IntegerField(blank=True, help_text='Billing zip code', null=True)),
                ('addr2', models.IntegerField(blank=True, help_text='Billing country code', null=True)),
                ('dist1', models.FloatField(blank=True, help_text='Distance between card & billing address', null=True)),
                ('dist2', models.FloatField(blank=True, help_text='Distance between card & billing zip', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=256)),
                ('c_features', models.JSONField(blank=True, help_text='C1–C15 count features', null=True)),
                ('d_features', models.JSONField(blank=True, help_text='D1–D15 timedelta features', null=True)),
                ('m_features', models.JSONField(blank=True, help_text='M1–M9 boolean match features', null=True)),
                ('v_features', models.JSONField(blank=True, help_text='V1–V339 Vesta anonymized features', null=True)),
                ('fraud_score', models.FloatField(blank=True, help_text='0–1 probability of fraud', null=True)),
                ('flag_layer', models.CharField(choices=[('none', 'None'), ('rule', 'Rule Engine'), ('model', 'ML Model')], default='none', max_length=8)),
                ('model_version', models.CharField(blank=True, help_text='Identifier of the model that scored this', max_length=64)),
                ('feature_snapshot', models.JSONField(blank=True, help_text='Input feature values used to produce fraud_score', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('under_review', 'Under Review')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.merchantprofile')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalystDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined'), ('under_review', 'Escalate for Further Review')], max_length=16)),
                ('rationale', models.TextField(blank=True, help_text='Analyst notes justifying the decision')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.ForeignKey(limit_choices_to={'role': 'analyst'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_decision', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Analyst Decision',
                'verbose_name_plural': 'Analyst Decisions',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_71abbb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fraud_score'], name='transaction_fraud_s_d1c1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['flag_layer'], name='transaction_flag_la_9aecf5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['occurred_at'], name='transaction_occurre_e78bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer'], name='transaction_custome_a08692_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['merchant'], name='transaction_merchan_bd7cce_idx'),
        ),
    ]
