# Generated by Django 6.1.1 on 2026-09-18 04:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('submitted_at', models.DateTimeField()),
                ('fraud_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('under_review', 'Under Review')], default='pending', max_length=16)),
                ('flagged_by', models.CharField(choices=[('none', 'None'), ('rule', 'Rule Engine'), ('model', 'ML Model')], default='none', max_length=8)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('feature_snapshot', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.merchantprofile')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalystDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=16)),
                ('analyst', models.ForeignKey(limit_choices_to={'role': 'analyst'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_decision', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Analyst Decision',
                'verbose_name_plural': 'Analyst Decisions',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_71abbb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['fraud_score'], name='transaction_fraud_s_d1c1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['flagged_by'], name='transaction_flagged_6fae8a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['submitted_at'], name='transaction_submitt_663062_idx'),
        ),
    ]
