# Generated by Django 6.1.1 on 2026-09-06 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=32)),
                ('algorithm', models.CharField(choices=[('random_forest', 'Random Forest'), ('logistic_regression', 'Logistic Regression'), ('gradient_boosting', 'Gradient Boosting'), ('xgboost', 'XGBoost')], max_length=64)),
                ('description', models.TextField(blank=True)),
                ('model_file', models.FileField(upload_to='ml_models/')),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=64)),
                ('input_features', models.JSONField()),
                ('fraud_score', models.FloatField()),
                ('is_fraud', models.BooleanField()),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ml_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='ml.mlmodel')),
            ],
            options={
                'verbose_name': 'Prediction Log',
                'verbose_name_plural': 'Prediction Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThresholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Threshold identifier, e.g. 'flag_score' or 'block_score'", max_length=64)),
                ('value', models.FloatField(help_text='New threshold value (0–1)')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('rationale', models.TextField(help_text='Required: reason for this change')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threshold_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Threshold Config',
                'verbose_name_plural': 'Threshold Configs',
                'ordering': ['-changed_at'],
                'get_latest_by': 'changed_at',
            },
        ),
    ]
