# Generated by Django 6.1.1 on 2026-10-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thresholdconfig',
            name='value',
        ),
        migrations.AddField(
            model_name='thresholdconfig',
            name='auto_block_threshold',
            field=models.FloatField(default=0.9, help_text='Scores above this are auto-declined'),
        ),
        migrations.AddField(
            model_name='thresholdconfig',
            name='flag_threshold',
            field=models.FloatField(default=0.75, help_text='Scores above this are flagged for manual review'),
        ),
    ]
